import type { CountryRaw } from './scoring'

export const DATABASE: CountryRaw[] = [
  // ── G7 ──────────────────────────────────────────────────────────────────
  { country:'United States', iso3:'USA', region:'América del Norte', bloc_primary:'G7',
    export_critical_bn:285, forex_reserves_bn:246, energy_net_export:12, food_self_suff:130,
    gdp_bn:25464, supply_chain_centrality:95, import_strategic_dep:3, us_export_pct:0,
    import_concentration_hhi:0.08, sanctions_regime:'none',
    ntm_density:78, export_control_score:10, standards_power:95, compliance_burden:55,
    institutional_signal:92, think_tank_consensus:88, strategic_concept_density:98,
    fdi_quality:68, sovereign_capex_signal:85, multi_alignment:5, shock_score:1.5,
    theme_energy:8, theme_chips:10, theme_minerals:7, theme_food:7,
    theme_shipping:6, theme_defense:10, theme_ai:10 },

  { country:'Germany', iso3:'DEU', region:'Europa Occidental', bloc_primary:'G7/UE',
    export_critical_bn:145, forex_reserves_bn:295, energy_net_export:-61, food_self_suff:93,
    gdp_bn:4072, supply_chain_centrality:78, import_strategic_dep:6, us_export_pct:9.5,
    import_concentration_hhi:0.14, sanctions_regime:'none',
    ntm_density:72, export_control_score:8, standards_power:82, compliance_burden:42,
    institutional_signal:75, think_tank_consensus:72, strategic_concept_density:78,
    fdi_quality:58, sovereign_capex_signal:62, multi_alignment:4, shock_score:3.5,
    theme_energy:5, theme_chips:7, theme_minerals:5, theme_food:5,
    theme_shipping:6, theme_defense:7, theme_ai:7 },

  { country:'Japan', iso3:'JPN', region:'Asia Oriental', bloc_primary:'G7/Quad',
    export_critical_bn:120, forex_reserves_bn:1291, energy_net_export:-85, food_self_suff:38,
    gdp_bn:4231, supply_chain_centrality:72, import_strategic_dep:8, us_export_pct:19,
    import_concentration_hhi:0.18, sanctions_regime:'none',
    ntm_density:65, export_control_score:8, standards_power:78, compliance_burden:48,
    institutional_signal:70, think_tank_consensus:68, strategic_concept_density:72,
    fdi_quality:55, sovereign_capex_signal:60, multi_alignment:4, shock_score:2.0,
    theme_energy:3, theme_chips:9, theme_minerals:4, theme_food:3,
    theme_shipping:7, theme_defense:7, theme_ai:8 },

  { country:'France', iso3:'FRA', region:'Europa Occidental', bloc_primary:'G7/UE',
    export_critical_bn:85, forex_reserves_bn:242, energy_net_export:-45, food_self_suff:122,
    gdp_bn:2784, supply_chain_centrality:65, import_strategic_dep:5, us_export_pct:7.5,
    import_concentration_hhi:0.12, sanctions_regime:'none',
    ntm_density:70, export_control_score:8, standards_power:80, compliance_burden:40,
    institutional_signal:72, think_tank_consensus:68, strategic_concept_density:74,
    fdi_quality:55, sovereign_capex_signal:60, multi_alignment:4, shock_score:2.5,
    theme_energy:6, theme_chips:6, theme_minerals:5, theme_food:6,
    theme_shipping:5, theme_defense:8, theme_ai:7 },

  { country:'Canada', iso3:'CAN', region:'América del Norte', bloc_primary:'G7',
    export_critical_bn:210, forex_reserves_bn:106, energy_net_export:58, food_self_suff:185,
    gdp_bn:2140, supply_chain_centrality:58, import_strategic_dep:3, us_export_pct:73.2,
    import_concentration_hhi:0.55, sanctions_regime:'none',
    ntm_density:60, export_control_score:8, standards_power:68, compliance_burden:38,
    institutional_signal:62, think_tank_consensus:60, strategic_concept_density:65,
    fdi_quality:52, sovereign_capex_signal:55, multi_alignment:4, shock_score:1.5,
    theme_energy:8, theme_chips:5, theme_minerals:8, theme_food:8,
    theme_shipping:5, theme_defense:7, theme_ai:6 },

  { country:'United Kingdom', iso3:'GBR', region:'Europa Occidental', bloc_primary:'G7',
    export_critical_bn:92, forex_reserves_bn:178, energy_net_export:-25, food_self_suff:68,
    gdp_bn:3071, supply_chain_centrality:68, import_strategic_dep:5, us_export_pct:12,
    import_concentration_hhi:0.15, sanctions_regime:'none',
    ntm_density:62, export_control_score:9, standards_power:75, compliance_burden:35,
    institutional_signal:80, think_tank_consensus:82, strategic_concept_density:80,
    fdi_quality:60, sovereign_capex_signal:65, multi_alignment:5, shock_score:2.0,
    theme_energy:5, theme_chips:6, theme_minerals:5, theme_food:4,
    theme_shipping:7, theme_defense:8, theme_ai:8 },

  { country:'Italy', iso3:'ITA', region:'Europa Occidental', bloc_primary:'G7/UE',
    export_critical_bn:72, forex_reserves_bn:195, energy_net_export:-70, food_self_suff:78,
    gdp_bn:2010, supply_chain_centrality:55, import_strategic_dep:7, us_export_pct:8.5,
    import_concentration_hhi:0.18, sanctions_regime:'none',
    ntm_density:65, export_control_score:7, standards_power:65, compliance_burden:52,
    institutional_signal:55, think_tank_consensus:50, strategic_concept_density:58,
    fdi_quality:42, sovereign_capex_signal:45, multi_alignment:3, shock_score:3.0,
    theme_energy:4, theme_chips:5, theme_minerals:4, theme_food:6,
    theme_shipping:5, theme_defense:5, theme_ai:5 },

  // ── BRICS ────────────────────────────────────────────────────────────────
  { country:'China', iso3:'CHN', region:'Asia Oriental', bloc_primary:'BRICS',
    export_critical_bn:580, forex_reserves_bn:3200, energy_net_export:-18, food_self_suff:95,
    gdp_bn:17963, supply_chain_centrality:92, import_strategic_dep:5, us_export_pct:16.8,
    import_concentration_hhi:0.12, sanctions_regime:'sectoral',
    ntm_density:85, export_control_score:7, standards_power:72, compliance_burden:68,
    institutional_signal:88, think_tank_consensus:80, strategic_concept_density:90,
    fdi_quality:48, sovereign_capex_signal:80, multi_alignment:4, shock_score:4.5,
    theme_energy:6, theme_chips:8, theme_minerals:9, theme_food:5,
    theme_shipping:9, theme_defense:9, theme_ai:9 },

  { country:'Russia', iso3:'RUS', region:'Europa del Este', bloc_primary:'BRICS',
    export_critical_bn:480, forex_reserves_bn:640, energy_net_export:87, food_self_suff:145,
    gdp_bn:2245, supply_chain_centrality:42, import_strategic_dep:4, us_export_pct:1.2,
    import_concentration_hhi:0.15, sanctions_regime:'partial',
    ntm_density:55, export_control_score:4, standards_power:38, compliance_burden:72,
    institutional_signal:78, think_tank_consensus:75, strategic_concept_density:85,
    fdi_quality:25, sovereign_capex_signal:20, multi_alignment:3, shock_score:9.0,
    theme_energy:10, theme_chips:3, theme_minerals:8, theme_food:8,
    theme_shipping:4, theme_defense:9, theme_ai:4 },

  { country:'India', iso3:'IND', region:'Asia del Sur', bloc_primary:'Quad/BRICS',
    export_critical_bn:95, forex_reserves_bn:562, energy_net_export:-38, food_self_suff:102,
    gdp_bn:3385, supply_chain_centrality:55, import_strategic_dep:5, us_export_pct:18.2,
    import_concentration_hhi:0.14, sanctions_regime:'none',
    ntm_density:72, export_control_score:5, standards_power:52, compliance_burden:60,
    institutional_signal:75, think_tank_consensus:70, strategic_concept_density:72,
    fdi_quality:38, sovereign_capex_signal:55, multi_alignment:5, shock_score:2.0,
    theme_energy:5, theme_chips:6, theme_minerals:5, theme_food:6,
    theme_shipping:5, theme_defense:7, theme_ai:7 },

  { country:'Brazil', iso3:'BRA', region:'América del Sur', bloc_primary:'BRICS',
    export_critical_bn:110, forex_reserves_bn:325, energy_net_export:3, food_self_suff:190,
    gdp_bn:1920, supply_chain_centrality:42, import_strategic_dep:4, us_export_pct:11,
    import_concentration_hhi:0.13, sanctions_regime:'none',
    ntm_density:60, export_control_score:3, standards_power:40, compliance_burden:70,
    institutional_signal:58, think_tank_consensus:52, strategic_concept_density:55,
    fdi_quality:32, sovereign_capex_signal:42, multi_alignment:3, shock_score:2.5,
    theme_energy:6, theme_chips:3, theme_minerals:6, theme_food:9,
    theme_shipping:4, theme_defense:4, theme_ai:4 },

  { country:'South Africa', iso3:'ZAF', region:'África Subsahariana', bloc_primary:'BRICS',
    export_critical_bn:52, forex_reserves_bn:60, energy_net_export:-15, food_self_suff:98,
    gdp_bn:406, supply_chain_centrality:35, import_strategic_dep:5, us_export_pct:8.9,
    import_concentration_hhi:0.20, sanctions_regime:'none',
    ntm_density:48, export_control_score:3, standards_power:35, compliance_burden:58,
    institutional_signal:48, think_tank_consensus:42, strategic_concept_density:45,
    fdi_quality:28, sovereign_capex_signal:32, multi_alignment:3, shock_score:2.0,
    theme_energy:4, theme_chips:2, theme_minerals:8, theme_food:4,
    theme_shipping:3, theme_defense:3, theme_ai:3 },

  // ── ORIENTE MEDIO ────────────────────────────────────────────────────────
  { country:'Saudi Arabia', iso3:'SAU', region:'Oriente Medio', bloc_primary:'GCC',
    export_critical_bn:320, forex_reserves_bn:478, energy_net_export:350, food_self_suff:42,
    gdp_bn:1109, supply_chain_centrality:48, import_strategic_dep:6, us_export_pct:8.5,
    import_concentration_hhi:0.22, sanctions_regime:'targeted',
    ntm_density:52, export_control_score:4, standards_power:42, compliance_burden:45,
    institutional_signal:68, think_tank_consensus:62, strategic_concept_density:70,
    fdi_quality:35, sovereign_capex_signal:72, multi_alignment:3, shock_score:2.5,
    theme_energy:10, theme_chips:3, theme_minerals:5, theme_food:3,
    theme_shipping:5, theme_defense:6, theme_ai:5 },

  { country:'Iran', iso3:'IRN', region:'Oriente Medio', bloc_primary:'Eje',
    export_critical_bn:45, forex_reserves_bn:15, energy_net_export:220, food_self_suff:72,
    gdp_bn:367, supply_chain_centrality:22, import_strategic_dep:6, us_export_pct:0,
    import_concentration_hhi:0.35, sanctions_regime:'maximum',
    ntm_density:38, export_control_score:0, standards_power:18, compliance_burden:90,
    institutional_signal:55, think_tank_consensus:60, strategic_concept_density:65,
    fdi_quality:8, sovereign_capex_signal:5, multi_alignment:2, shock_score:8.5,
    theme_energy:9, theme_chips:2, theme_minerals:4, theme_food:3,
    theme_shipping:3, theme_defense:7, theme_ai:2 },

  { country:'UAE', iso3:'ARE', region:'Oriente Medio', bloc_primary:'GCC',
    export_critical_bn:165, forex_reserves_bn:188, energy_net_export:280, food_self_suff:25,
    gdp_bn:509, supply_chain_centrality:60, import_strategic_dep:5, us_export_pct:4.8,
    import_concentration_hhi:0.22, sanctions_regime:'targeted',
    ntm_density:50, export_control_score:4, standards_power:45, compliance_burden:35,
    institutional_signal:60, think_tank_consensus:55, strategic_concept_density:62,
    fdi_quality:42, sovereign_capex_signal:78, multi_alignment:4, shock_score:2.0,
    theme_energy:8, theme_chips:4, theme_minerals:4, theme_food:3,
    theme_shipping:7, theme_defense:5, theme_ai:6 },

  { country:'Turkey', iso3:'TUR', region:'Europa/Oriente Medio', bloc_primary:'NATO+',
    export_critical_bn:35, forex_reserves_bn:128, energy_net_export:-72, food_self_suff:97,
    gdp_bn:906, supply_chain_centrality:48, import_strategic_dep:7, us_export_pct:6.5,
    import_concentration_hhi:0.18, sanctions_regime:'targeted',
    ntm_density:58, export_control_score:5, standards_power:48, compliance_burden:60,
    institutional_signal:58, think_tank_consensus:52, strategic_concept_density:58,
    fdi_quality:32, sovereign_capex_signal:38, multi_alignment:4, shock_score:3.5,
    theme_energy:4, theme_chips:4, theme_minerals:4, theme_food:5,
    theme_shipping:6, theme_defense:6, theme_ai:4 },

  { country:'Israel', iso3:'ISR', region:'Oriente Medio', bloc_primary:'Occidental',
    export_critical_bn:45, forex_reserves_bn:204, energy_net_export:-20, food_self_suff:52,
    gdp_bn:522, supply_chain_centrality:38, import_strategic_dep:5, us_export_pct:28,
    import_concentration_hhi:0.30, sanctions_regime:'none',
    ntm_density:55, export_control_score:7, standards_power:55, compliance_burden:48,
    institutional_signal:65, think_tank_consensus:60, strategic_concept_density:68,
    fdi_quality:62, sovereign_capex_signal:55, multi_alignment:2, shock_score:7.0,
    theme_energy:4, theme_chips:8, theme_minerals:3, theme_food:3,
    theme_shipping:3, theme_defense:9, theme_ai:8 },

  { country:'Qatar', iso3:'QAT', region:'Oriente Medio', bloc_primary:'GCC',
    export_critical_bn:78, forex_reserves_bn:48, energy_net_export:400, food_self_suff:15,
    gdp_bn:237, supply_chain_centrality:35, import_strategic_dep:7, us_export_pct:2,
    import_concentration_hhi:0.30, sanctions_regime:'none',
    ntm_density:42, export_control_score:3, standards_power:32, compliance_burden:32,
    institutional_signal:50, think_tank_consensus:48, strategic_concept_density:52,
    fdi_quality:30, sovereign_capex_signal:80, multi_alignment:2, shock_score:2.0,
    theme_energy:10, theme_chips:3, theme_minerals:3, theme_food:2,
    theme_shipping:5, theme_defense:4, theme_ai:4 },

  // ── ASIA-PACÍFICO ────────────────────────────────────────────────────────
  { country:'South Korea', iso3:'KOR', region:'Asia Oriental', bloc_primary:'Quad+',
    export_critical_bn:175, forex_reserves_bn:423, energy_net_export:-78, food_self_suff:45,
    gdp_bn:1665, supply_chain_centrality:65, import_strategic_dep:7, us_export_pct:16.1,
    import_concentration_hhi:0.20, sanctions_regime:'none',
    ntm_density:60, export_control_score:7, standards_power:70, compliance_burden:42,
    institutional_signal:65, think_tank_consensus:60, strategic_concept_density:68,
    fdi_quality:58, sovereign_capex_signal:62, multi_alignment:3, shock_score:2.5,
    theme_energy:3, theme_chips:10, theme_minerals:4, theme_food:3,
    theme_shipping:6, theme_defense:7, theme_ai:8 },

  { country:'Taiwan', iso3:'TWN', region:'Asia Oriental', bloc_primary:'Occidental+',
    export_critical_bn:125, forex_reserves_bn:558, energy_net_export:-90, food_self_suff:32,
    gdp_bn:761, supply_chain_centrality:70, import_strategic_dep:8, us_export_pct:18,
    import_concentration_hhi:0.25, sanctions_regime:'none',
    ntm_density:55, export_control_score:6, standards_power:65, compliance_burden:40,
    institutional_signal:72, think_tank_consensus:78, strategic_concept_density:85,
    fdi_quality:72, sovereign_capex_signal:65, multi_alignment:2, shock_score:7.5,
    theme_energy:2, theme_chips:10, theme_minerals:3, theme_food:2,
    theme_shipping:5, theme_defense:8, theme_ai:9 },

  { country:'Australia', iso3:'AUS', region:'Oceanía', bloc_primary:'Quad/AUKUS',
    export_critical_bn:185, forex_reserves_bn:58, energy_net_export:45, food_self_suff:250,
    gdp_bn:1724, supply_chain_centrality:42, import_strategic_dep:4, us_export_pct:5,
    import_concentration_hhi:0.30, sanctions_regime:'none',
    ntm_density:52, export_control_score:8, standards_power:55, compliance_burden:35,
    institutional_signal:62, think_tank_consensus:60, strategic_concept_density:65,
    fdi_quality:48, sovereign_capex_signal:52, multi_alignment:4, shock_score:2.0,
    theme_energy:7, theme_chips:4, theme_minerals:9, theme_food:8,
    theme_shipping:5, theme_defense:7, theme_ai:5 },

  { country:'Vietnam', iso3:'VNM', region:'Asia Sudoriental', bloc_primary:'ASEAN',
    export_critical_bn:95, forex_reserves_bn:88, energy_net_export:-5, food_self_suff:105,
    gdp_bn:409, supply_chain_centrality:48, import_strategic_dep:6, us_export_pct:27.5,
    import_concentration_hhi:0.22, sanctions_regime:'none',
    ntm_density:55, export_control_score:2, standards_power:28, compliance_burden:58,
    institutional_signal:50, think_tank_consensus:48, strategic_concept_density:52,
    fdi_quality:45, sovereign_capex_signal:50, multi_alignment:3, shock_score:2.0,
    theme_energy:3, theme_chips:6, theme_minerals:4, theme_food:5,
    theme_shipping:5, theme_defense:4, theme_ai:4 },

  { country:'Indonesia', iso3:'IDN', region:'Asia Sudoriental', bloc_primary:'G20/ASEAN',
    export_critical_bn:72, forex_reserves_bn:137, energy_net_export:12, food_self_suff:88,
    gdp_bn:1319, supply_chain_centrality:42, import_strategic_dep:5, us_export_pct:9.8,
    import_concentration_hhi:0.18, sanctions_regime:'none',
    ntm_density:58, export_control_score:3, standards_power:32, compliance_burden:62,
    institutional_signal:52, think_tank_consensus:48, strategic_concept_density:52,
    fdi_quality:30, sovereign_capex_signal:45, multi_alignment:3, shock_score:1.5,
    theme_energy:5, theme_chips:3, theme_minerals:7, theme_food:4,
    theme_shipping:5, theme_defense:4, theme_ai:3 },

  { country:'Malaysia', iso3:'MYS', region:'Asia Sudoriental', bloc_primary:'ASEAN',
    export_critical_bn:65, forex_reserves_bn:115, energy_net_export:20, food_self_suff:72,
    gdp_bn:407, supply_chain_centrality:52, import_strategic_dep:6, us_export_pct:12,
    import_concentration_hhi:0.22, sanctions_regime:'none',
    ntm_density:52, export_control_score:3, standards_power:35, compliance_burden:50,
    institutional_signal:45, think_tank_consensus:42, strategic_concept_density:48,
    fdi_quality:42, sovereign_capex_signal:45, multi_alignment:2, shock_score:1.5,
    theme_energy:5, theme_chips:5, theme_minerals:4, theme_food:4,
    theme_shipping:5, theme_defense:3, theme_ai:4 },

  { country:'Thailand', iso3:'THA', region:'Asia Sudoriental', bloc_primary:'ASEAN',
    export_critical_bn:55, forex_reserves_bn:225, energy_net_export:-15, food_self_suff:125,
    gdp_bn:495, supply_chain_centrality:45, import_strategic_dep:5, us_export_pct:12,
    import_concentration_hhi:0.18, sanctions_regime:'none',
    ntm_density:55, export_control_score:2, standards_power:30, compliance_burden:55,
    institutional_signal:42, think_tank_consensus:38, strategic_concept_density:42,
    fdi_quality:32, sovereign_capex_signal:38, multi_alignment:2, shock_score:1.5,
    theme_energy:3, theme_chips:4, theme_minerals:3, theme_food:6,
    theme_shipping:4, theme_defense:3, theme_ai:3 },

  // ── EUROPA ───────────────────────────────────────────────────────────────
  { country:'Netherlands', iso3:'NLD', region:'Europa Occidental', bloc_primary:'UE',
    export_critical_bn:88, forex_reserves_bn:55, energy_net_export:-30, food_self_suff:180,
    gdp_bn:1011, supply_chain_centrality:68, import_strategic_dep:5, us_export_pct:5.5,
    import_concentration_hhi:0.12, sanctions_regime:'none',
    ntm_density:68, export_control_score:9, standards_power:72, compliance_burden:38,
    institutional_signal:65, think_tank_consensus:62, strategic_concept_density:68,
    fdi_quality:55, sovereign_capex_signal:58, multi_alignment:3, shock_score:2.5,
    theme_energy:4, theme_chips:10, theme_minerals:4, theme_food:7,
    theme_shipping:8, theme_defense:6, theme_ai:7 },

  { country:'Poland', iso3:'POL', region:'Europa del Este', bloc_primary:'UE/NATO',
    export_critical_bn:28, forex_reserves_bn:168, energy_net_export:-48, food_self_suff:108,
    gdp_bn:688, supply_chain_centrality:42, import_strategic_dep:6, us_export_pct:3.1,
    import_concentration_hhi:0.18, sanctions_regime:'none',
    ntm_density:60, export_control_score:6, standards_power:45, compliance_burden:52,
    institutional_signal:52, think_tank_consensus:50, strategic_concept_density:55,
    fdi_quality:42, sovereign_capex_signal:48, multi_alignment:3, shock_score:3.0,
    theme_energy:4, theme_chips:4, theme_minerals:4, theme_food:5,
    theme_shipping:3, theme_defense:7, theme_ai:4 },

  { country:'Czech Republic', iso3:'CZE', region:'Europa Central', bloc_primary:'UE/NATO',
    export_critical_bn:45, forex_reserves_bn:148, energy_net_export:-25, food_self_suff:85,
    gdp_bn:291, supply_chain_centrality:45, import_strategic_dep:6, us_export_pct:3,
    import_concentration_hhi:0.12, sanctions_regime:'none',
    ntm_density:65, export_control_score:6, standards_power:55, compliance_burden:45,
    institutional_signal:60, think_tank_consensus:58, strategic_concept_density:62,
    fdi_quality:45, sovereign_capex_signal:50, multi_alignment:3, shock_score:2.5,
    theme_energy:4, theme_chips:5, theme_minerals:4, theme_food:5,
    theme_shipping:4, theme_defense:5, theme_ai:5 },

  { country:'Norway', iso3:'NOR', region:'Europa Occidental', bloc_primary:'NATO',
    export_critical_bn:105, forex_reserves_bn:82, energy_net_export:280, food_self_suff:85,
    gdp_bn:582, supply_chain_centrality:38, import_strategic_dep:4, us_export_pct:4,
    import_concentration_hhi:0.15, sanctions_regime:'none',
    ntm_density:55, export_control_score:7, standards_power:52, compliance_burden:32,
    institutional_signal:55, think_tank_consensus:52, strategic_concept_density:55,
    fdi_quality:45, sovereign_capex_signal:85, multi_alignment:2, shock_score:1.5,
    theme_energy:9, theme_chips:4, theme_minerals:6, theme_food:5,
    theme_shipping:6, theme_defense:5, theme_ai:5 },

  { country:'Switzerland', iso3:'CHE', region:'Europa Occidental', bloc_primary:'Neutral',
    export_critical_bn:52, forex_reserves_bn:880, energy_net_export:-40, food_self_suff:50,
    gdp_bn:807, supply_chain_centrality:50, import_strategic_dep:5, us_export_pct:9,
    import_concentration_hhi:0.15, sanctions_regime:'none',
    ntm_density:58, export_control_score:6, standards_power:60, compliance_burden:35,
    institutional_signal:60, think_tank_consensus:55, strategic_concept_density:60,
    fdi_quality:60, sovereign_capex_signal:65, multi_alignment:2, shock_score:1.5,
    theme_energy:4, theme_chips:5, theme_minerals:5, theme_food:4,
    theme_shipping:4, theme_defense:4, theme_ai:6 },

  { country:'Spain', iso3:'ESP', region:'Europa Occidental', bloc_primary:'UE/NATO',
    export_critical_bn:85, forex_reserves_bn:78, energy_net_export:-55, food_self_suff:75,
    gdp_bn:1426, supply_chain_centrality:55, import_strategic_dep:5, us_export_pct:5,
    import_concentration_hhi:0.14, sanctions_regime:'none',
    ntm_density:68, export_control_score:7, standards_power:65, compliance_burden:42,
    institutional_signal:62, think_tank_consensus:60, strategic_concept_density:65,
    fdi_quality:48, sovereign_capex_signal:55, multi_alignment:3, shock_score:2.0,
    theme_energy:5, theme_chips:6, theme_minerals:4, theme_food:5,
    theme_shipping:6, theme_defense:6, theme_ai:6 },

  { country:'Sweden', iso3:'SWE', region:'Europa Occidental', bloc_primary:'NATO',
    export_critical_bn:45, forex_reserves_bn:58, energy_net_export:25, food_self_suff:55,
    gdp_bn:593, supply_chain_centrality:42, import_strategic_dep:5, us_export_pct:4,
    import_concentration_hhi:0.15, sanctions_regime:'none',
    ntm_density:60, export_control_score:7, standards_power:58, compliance_burden:38,
    institutional_signal:65, think_tank_consensus:62, strategic_concept_density:68,
    fdi_quality:55, sovereign_capex_signal:60, multi_alignment:2, shock_score:1.5,
    theme_energy:7, theme_chips:6, theme_minerals:5, theme_food:4,
    theme_shipping:5, theme_defense:6, theme_ai:7 },

  { country:'Austria', iso3:'AUT', region:'Europa Occidental', bloc_primary:'UE',
    export_critical_bn:35, forex_reserves_bn:35, energy_net_export:-15, food_self_suff:85,
    gdp_bn:515, supply_chain_centrality:48, import_strategic_dep:5, us_export_pct:4,
    import_concentration_hhi:0.12, sanctions_regime:'none',
    ntm_density:65, export_control_score:7, standards_power:62, compliance_burden:40,
    institutional_signal:65, think_tank_consensus:62, strategic_concept_density:68,
    fdi_quality:52, sovereign_capex_signal:58, multi_alignment:2, shock_score:2.0,
    theme_energy:5, theme_chips:5, theme_minerals:4, theme_food:6,
    theme_shipping:4, theme_defense:5, theme_ai:6 },

  { country:'Belgium', iso3:'BEL', region:'Europa Occidental', bloc_primary:'UE/NATO',
    export_critical_bn:55, forex_reserves_bn:40, energy_net_export:-45, food_self_suff:55,
    gdp_bn:632, supply_chain_centrality:58, import_strategic_dep:5, us_export_pct:5,
    import_concentration_hhi:0.14, sanctions_regime:'none',
    ntm_density:68, export_control_score:8, standards_power:68, compliance_burden:38,
    institutional_signal:68, think_tank_consensus:65, strategic_concept_density:70,
    fdi_quality:55, sovereign_capex_signal:60, multi_alignment:3, shock_score:2.0,
    theme_energy:4, theme_chips:7, theme_minerals:4, theme_food:4,
    theme_shipping:6, theme_defense:6, theme_ai:7 },

  { country:'Portugal', iso3:'PRT', region:'Europa Occidental', bloc_primary:'UE/NATO',
    export_critical_bn:25, forex_reserves_bn:32, energy_net_export:-20, food_self_suff:65,
    gdp_bn:289, supply_chain_centrality:38, import_strategic_dep:6, us_export_pct:3,
    import_concentration_hhi:0.18, sanctions_regime:'none',
    ntm_density:62, export_control_score:6, standards_power:55, compliance_burden:45,
    institutional_signal:58, think_tank_consensus:55, strategic_concept_density:60,
    fdi_quality:45, sovereign_capex_signal:50, multi_alignment:3, shock_score:2.0,
    theme_energy:4, theme_chips:4, theme_minerals:3, theme_food:5,
    theme_shipping:5, theme_defense:5, theme_ai:5 },

  // ── LATINOAMÉRICA ────────────────────────────────────────────────────────
  { country:'Mexico', iso3:'MEX', region:'América del Norte', bloc_primary:'TMEC',
    export_critical_bn:55, forex_reserves_bn:201, energy_net_export:-22, food_self_suff:85,
    gdp_bn:1294, supply_chain_centrality:48, import_strategic_dep:6, us_export_pct:79.95,
    import_concentration_hhi:0.68, sanctions_regime:'none',
    ntm_density:50, export_control_score:3, standards_power:35, compliance_burden:65,
    institutional_signal:52, think_tank_consensus:50, strategic_concept_density:55,
    fdi_quality:35, sovereign_capex_signal:42, multi_alignment:2, shock_score:3.0,
    theme_energy:4, theme_chips:4, theme_minerals:5, theme_food:4,
    theme_shipping:4, theme_defense:3, theme_ai:3 },

  { country:'Argentina', iso3:'ARG', region:'América del Sur', bloc_primary:'BRICS+',
    export_critical_bn:38, forex_reserves_bn:25, energy_net_export:-5, food_self_suff:200,
    gdp_bn:632, supply_chain_centrality:32, import_strategic_dep:5, us_export_pct:4.7,
    import_concentration_hhi:0.18, sanctions_regime:'none',
    ntm_density:55, export_control_score:2, standards_power:28, compliance_burden:75,
    institutional_signal:45, think_tank_consensus:42, strategic_concept_density:45,
    fdi_quality:22, sovereign_capex_signal:28, multi_alignment:3, shock_score:5.0,
    theme_energy:5, theme_chips:2, theme_minerals:6, theme_food:9,
    theme_shipping:3, theme_defense:2, theme_ai:2 },

  { country:'Chile', iso3:'CHL', region:'América del Sur', bloc_primary:'Alianza Pacífico',
    export_critical_bn:42, forex_reserves_bn:42, energy_net_export:-30, food_self_suff:90,
    gdp_bn:301, supply_chain_centrality:30, import_strategic_dep:5, us_export_pct:8,
    import_concentration_hhi:0.22, sanctions_regime:'none',
    ntm_density:45, export_control_score:3, standards_power:30, compliance_burden:50,
    institutional_signal:42, think_tank_consensus:38, strategic_concept_density:42,
    fdi_quality:28, sovereign_capex_signal:35, multi_alignment:2, shock_score:2.0,
    theme_energy:4, theme_chips:2, theme_minerals:9, theme_food:5,
    theme_shipping:4, theme_defense:2, theme_ai:2 },

  { country:'Colombia', iso3:'COL', region:'América del Sur', bloc_primary:'Alianza Pacífico',
    export_critical_bn:28, forex_reserves_bn:58, energy_net_export:20, food_self_suff:90,
    gdp_bn:343, supply_chain_centrality:28, import_strategic_dep:5, us_export_pct:28,
    import_concentration_hhi:0.32, sanctions_regime:'none',
    ntm_density:45, export_control_score:2, standards_power:25, compliance_burden:62,
    institutional_signal:40, think_tank_consensus:38, strategic_concept_density:40,
    fdi_quality:22, sovereign_capex_signal:28, multi_alignment:2, shock_score:2.0,
    theme_energy:5, theme_chips:2, theme_minerals:4, theme_food:5,
    theme_shipping:3, theme_defense:3, theme_ai:2 },

  { country:'Uruguay', iso3:'URY', region:'América del Sur', bloc_primary:'Mercosur',
    export_critical_bn:8, forex_reserves_bn:18, energy_net_export:0, food_self_suff:120,
    gdp_bn:81, supply_chain_centrality:25, import_strategic_dep:5, us_export_pct:5,
    import_concentration_hhi:0.20, sanctions_regime:'none',
    ntm_density:55, export_control_score:3, standards_power:35, compliance_burden:55,
    institutional_signal:45, think_tank_consensus:42, strategic_concept_density:45,
    fdi_quality:35, sovereign_capex_signal:40, multi_alignment:2, shock_score:2.0,
    theme_energy:4, theme_chips:2, theme_minerals:3, theme_food:8,
    theme_shipping:4, theme_defense:3, theme_ai:2 },

  { country:'Ecuador', iso3:'ECU', region:'América del Sur', bloc_primary:'Alianza Pacífico',
    export_critical_bn:12, forex_reserves_bn:8, energy_net_export:15, food_self_suff:75,
    gdp_bn:121, supply_chain_centrality:22, import_strategic_dep:6, us_export_pct:25,
    import_concentration_hhi:0.28, sanctions_regime:'none',
    ntm_density:48, export_control_score:2, standards_power:25, compliance_burden:65,
    institutional_signal:38, think_tank_consensus:35, strategic_concept_density:38,
    fdi_quality:20, sovereign_capex_signal:25, multi_alignment:2, shock_score:3.0,
    theme_energy:6, theme_chips:2, theme_minerals:4, theme_food:4,
    theme_shipping:3, theme_defense:2, theme_ai:2 },

  // ── ÁFRICA ───────────────────────────────────────────────────────────────
  { country:'Nigeria', iso3:'NGA', region:'África Subsahariana', bloc_primary:'AU/ECOWAS',
    export_critical_bn:48, forex_reserves_bn:38, energy_net_export:95, food_self_suff:82,
    gdp_bn:477, supply_chain_centrality:28, import_strategic_dep:5, us_export_pct:6.5,
    import_concentration_hhi:0.22, sanctions_regime:'none',
    ntm_density:42, export_control_score:1, standards_power:22, compliance_burden:72,
    institutional_signal:42, think_tank_consensus:38, strategic_concept_density:42,
    fdi_quality:18, sovereign_capex_signal:25, multi_alignment:2, shock_score:3.0,
    theme_energy:8, theme_chips:1, theme_minerals:4, theme_food:4,
    theme_shipping:3, theme_defense:3, theme_ai:2 },

  { country:'Egypt', iso3:'EGY', region:'África del Norte', bloc_primary:'AU/AL',
    export_critical_bn:35, forex_reserves_bn:35, energy_net_export:-5, food_self_suff:55,
    gdp_bn:476, supply_chain_centrality:38, import_strategic_dep:6, us_export_pct:8,
    import_concentration_hhi:0.25, sanctions_regime:'none',
    ntm_density:48, export_control_score:2, standards_power:28, compliance_burden:68,
    institutional_signal:45, think_tank_consensus:42, strategic_concept_density:45,
    fdi_quality:22, sovereign_capex_signal:30, multi_alignment:3, shock_score:3.5,
    theme_energy:4, theme_chips:2, theme_minerals:3, theme_food:4,
    theme_shipping:7, theme_defense:4, theme_ai:2 },

  { country:'Morocco', iso3:'MAR', region:'África del Norte', bloc_primary:'UE+',
    export_critical_bn:22, forex_reserves_bn:35, energy_net_export:-40, food_self_suff:72,
    gdp_bn:134, supply_chain_centrality:32, import_strategic_dep:6, us_export_pct:3,
    import_concentration_hhi:0.28, sanctions_regime:'none',
    ntm_density:45, export_control_score:2, standards_power:28, compliance_burden:58,
    institutional_signal:40, think_tank_consensus:38, strategic_concept_density:42,
    fdi_quality:25, sovereign_capex_signal:32, multi_alignment:2, shock_score:1.5,
    theme_energy:3, theme_chips:2, theme_minerals:7, theme_food:4,
    theme_shipping:3, theme_defense:3, theme_ai:2 },

  { country:'Ethiopia', iso3:'ETH', region:'África Subsahariana', bloc_primary:'AU/BRICS',
    export_critical_bn:4, forex_reserves_bn:3, energy_net_export:-15, food_self_suff:72,
    gdp_bn:127, supply_chain_centrality:15, import_strategic_dep:7, us_export_pct:5,
    import_concentration_hhi:0.40, sanctions_regime:'none',
    ntm_density:30, export_control_score:1, standards_power:12, compliance_burden:72,
    institutional_signal:32, think_tank_consensus:30, strategic_concept_density:32,
    fdi_quality:12, sovereign_capex_signal:15, multi_alignment:3, shock_score:3.5,
    theme_energy:2, theme_chips:1, theme_minerals:3, theme_food:3,
    theme_shipping:2, theme_defense:3, theme_ai:1 },

  // ── OTROS ────────────────────────────────────────────────────────────────
  { country:'Kazakhstan', iso3:'KAZ', region:'Asia Central', bloc_primary:'OCS/CSTO',
    export_critical_bn:65, forex_reserves_bn:94, energy_net_export:155, food_self_suff:112,
    gdp_bn:220, supply_chain_centrality:30, import_strategic_dep:5, us_export_pct:3.5,
    import_concentration_hhi:0.28, sanctions_regime:'targeted',
    ntm_density:38, export_control_score:2, standards_power:22, compliance_burden:65,
    institutional_signal:40, think_tank_consensus:38, strategic_concept_density:42,
    fdi_quality:22, sovereign_capex_signal:28, multi_alignment:3, shock_score:3.0,
    theme_energy:8, theme_chips:2, theme_minerals:7, theme_food:5,
    theme_shipping:3, theme_defense:4, theme_ai:2 },

  { country:'North Korea', iso3:'PRK', region:'Asia Oriental', bloc_primary:'Autárquico',
    export_critical_bn:1.8, forex_reserves_bn:2, energy_net_export:-25, food_self_suff:70,
    gdp_bn:18, supply_chain_centrality:5, import_strategic_dep:8, us_export_pct:0,
    import_concentration_hhi:0.90, sanctions_regime:'maximum',
    ntm_density:20, export_control_score:0, standards_power:5, compliance_burden:95,
    institutional_signal:48, think_tank_consensus:55, strategic_concept_density:60,
    fdi_quality:2, sovereign_capex_signal:2, multi_alignment:1, shock_score:8.0,
    theme_energy:2, theme_chips:1, theme_minerals:3, theme_food:2,
    theme_shipping:1, theme_defense:9, theme_ai:1 },

  { country:'Venezuela', iso3:'VEN', region:'América del Sur', bloc_primary:'ALBA',
    export_critical_bn:12, forex_reserves_bn:9, energy_net_export:180, food_self_suff:55,
    gdp_bn:98, supply_chain_centrality:15, import_strategic_dep:7, us_export_pct:2,
    import_concentration_hhi:0.65, sanctions_regime:'partial',
    ntm_density:30, export_control_score:0, standards_power:12, compliance_burden:85,
    institutional_signal:45, think_tank_consensus:48, strategic_concept_density:50,
    fdi_quality:5, sovereign_capex_signal:5, multi_alignment:2, shock_score:7.0,
    theme_energy:8, theme_chips:1, theme_minerals:4, theme_food:2,
    theme_shipping:2, theme_defense:4, theme_ai:1 },

  { country:'Pakistan', iso3:'PAK', region:'Asia del Sur', bloc_primary:'OCS',
    export_critical_bn:18, forex_reserves_bn:15, energy_net_export:-30, food_self_suff:75,
    gdp_bn:347, supply_chain_centrality:22, import_strategic_dep:7, us_export_pct:17,
    import_concentration_hhi:0.30, sanctions_regime:'none',
    ntm_density:40, export_control_score:2, standards_power:20, compliance_burden:75,
    institutional_signal:42, think_tank_consensus:40, strategic_concept_density:42,
    fdi_quality:15, sovereign_capex_signal:20, multi_alignment:3, shock_score:4.0,
    theme_energy:3, theme_chips:1, theme_minerals:3, theme_food:4,
    theme_shipping:2, theme_defense:4, theme_ai:2 },

  { country:'Philippines', iso3:'PHL', region:'Asia Sudoriental', bloc_primary:'ASEAN',
    export_critical_bn:25, forex_reserves_bn:98, energy_net_export:-35, food_self_suff:78,
    gdp_bn:404, supply_chain_centrality:30, import_strategic_dep:6, us_export_pct:16,
    import_concentration_hhi:0.25, sanctions_regime:'none',
    ntm_density:45, export_control_score:3, standards_power:25, compliance_burden:62,
    institutional_signal:40, think_tank_consensus:38, strategic_concept_density:40,
    fdi_quality:25, sovereign_capex_signal:30, multi_alignment:2, shock_score:2.5,
    theme_energy:3, theme_chips:3, theme_minerals:4, theme_food:4,
    theme_shipping:4, theme_defense:4, theme_ai:3 },

  { country:'Bangladesh', iso3:'BGD', region:'Asia del Sur', bloc_primary:'G77',
    export_critical_bn:12, forex_reserves_bn:32, energy_net_export:-20, food_self_suff:82,
    gdp_bn:460, supply_chain_centrality:22, import_strategic_dep:6, us_export_pct:20,
    import_concentration_hhi:0.35, sanctions_regime:'none',
    ntm_density:38, export_control_score:1, standards_power:18, compliance_burden:68,
    institutional_signal:35, think_tank_consensus:32, strategic_concept_density:35,
    fdi_quality:15, sovereign_capex_signal:18, multi_alignment:2, shock_score:2.5,
    theme_energy:2, theme_chips:1, theme_minerals:2, theme_food:4,
    theme_shipping:3, theme_defense:2, theme_ai:1 },

  { country:'Peru', iso3:'PER', region:'América del Sur', bloc_primary:'Alianza Pacífico',
    export_critical_bn:22, forex_reserves_bn:72, energy_net_export:5, food_self_suff:85,
    gdp_bn:242, supply_chain_centrality:25, import_strategic_dep:5, us_export_pct:18,
    import_concentration_hhi:0.28, sanctions_regime:'none',
    ntm_density:42, export_control_score:2, standards_power:22, compliance_burden:58,
    institutional_signal:38, think_tank_consensus:35, strategic_concept_density:38,
    fdi_quality:20, sovereign_capex_signal:25, multi_alignment:2, shock_score:2.0,
    theme_energy:3, theme_chips:1, theme_minerals:8, theme_food:5,
    theme_shipping:3, theme_defense:2, theme_ai:1 },
]

export const ALL_COUNTRIES = DATABASE.map(d => d.country).sort()
